#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");
var print = function (potato) { 
process.stdout.write(potato);
}
print(c.clear + c.multi("Welcome to Hetalia's Magic Eightball!" + "\n"));

